# log frequency
val_check_interval: 1.0

tqdm_progress_bar:
  refresh_rate: 20


wandb:
  project: DLAI-project
  entity: Caiserini
  log_model: True
  mode: 'online'
  name: 'Apple'
  save_dir: ${oc.env:PROJECT_ROOT}

wandb_watch:
  log: 'all'
  log_freq: 100

lr_monitor:
  logging_interval: "step"
  log_momentum: False
