# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - apple
    - no-time

defaults:
  - _self_
  - data: default
  - hydra: default
  - logging: default
  - model: default
  - optim: default
  - train: default
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib